all: libft

libft: libft.a

objects = ft_atoi.o ft_bzero.o ft_calloc.o ft_isalnum.o ft_isalpha.o ft_isascii.o\
ft_isdigit.o ft_isprint.o ft_itoa.o ft_memchr.o ft_memccpy.o ft_memcmp.o ft_memcpy.o\
ft_memmove.o ft_memset.o ft_putchar_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_putstr_fd.o ft_split.o\
ft_strchr.o ft_strdup.o ft_strjoin.o ft_strlcat.o ft_strlcpy.o ft_strlen.o ft_strmapi.o ft_strncmp.o\
ft_strnstr.o ft_strrchr.o ft_strtrim.o ft_strtrim.o ft_substr.o ft_tolower.o ft_toupper.o

bonusobjects = ft_lstclear.o ft_lstadd_back.o ft_lstadd_front.o ft_lstdelone.o ft_lstiter.o\
ft_lstmap.o ft_lstnew.o ft_lstsize.o ft_lstlast.o

ft_lstclear.o: ft_lstclear.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstclear.c

ft_lstadd_back.o: ft_lstadd_back.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstadd_back.c

ft_lstadd_front.o: ft_lstadd_front.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstadd_front.c

ft_lstdelone.o: ft_lstdelone.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstdelone.c

ft_lstlast.o: ft_lstlast.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstlast.c

ft_lstiter.o: ft_lstiter.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstiter.c

ft_lstmap.o: ft_lstmap.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstmap.c

ft_lstnew.o: ft_lstnew.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstnew.c

ft_lstsize.o: ft_lstsize.c libft.h
	gcc -c -Wall -Wextra -Werror ft_lstsize.c

ft_atoi.o: ft_atoi.c libft.h
	gcc -c -Wall -Wextra -Werror ft_atoi.c

ft_bzero.o: ft_bzero.c libft.h
	gcc -c -Wall -Wextra -Werror ft_bzero.c

ft_calloc.o: ft_calloc.c libft.h
	gcc -c -Wall -Wextra -Werror ft_calloc.c

ft_isalnum.o: ft_isalnum.c libft.h
	gcc -c -Wall -Wextra -Werror ft_isalnum.c

ft_isalpha.o: ft_isalpha.c libft.h
	gcc -c -Wall -Wextra -Werror ft_isalpha.c

ft_isascii.o: ft_isascii.c libft.h
	gcc -c -Wall -Wextra -Werror ft_isascii.c

ft_isdigit.o: ft_isdigit.c libft.h
	gcc -c -Wall -Wextra -Werror ft_isdigit.c

ft_isprint.o: ft_isprint.c libft.h
	gcc -c -Wall -Wextra -Werror ft_isprint.c

ft_itoa.o: ft_itoa.c libft.h
	gcc -c -Wall -Wextra -Werror ft_itoa.c

ft_memccpy.o: ft_memccpy.c libft.h
	gcc -c -Wall -Wextra -Werror ft_memccpy.c

ft_memcpy.o: ft_memcpy.c libft.h
	gcc -c -Wall -Wextra -Werror ft_memcpy.c

ft_memchr.o: ft_memchr.c libft.h
	gcc -c -Wall -Wextra -Werror ft_memchr.c

ft_memcmp.o: ft_memcmp.c libft.h
	gcc -c -Wall -Wextra -Werror ft_memcmp.c

ft_memmove.o: ft_memmove.c libft.h
	gcc -c -Wall -Wextra -Werror ft_memmove.c

ft_memset.o: ft_memset.c libft.h
	gcc -c -Wall -Wextra -Werror ft_memset.c

ft_putchar_fd.o: ft_putchar_fd.c libft.h
	gcc -c -Wall -Wextra -Werror ft_putchar_fd.c

ft_putendl_fd.o: ft_putendl_fd.c libft.h
	gcc -c -Wall -Wextra -Werror ft_putendl_fd.c

ft_putnbr_fd.o: ft_putnbr_fd.c libft.h
	gcc -c -Wall -Wextra -Werror ft_putnbr_fd.c

ft_putstr_fd.o: ft_putstr_fd.c libft.h
	gcc -c -Wall -Wextra -Werror ft_putstr_fd.c

ft_split.o: ft_split.c libft.h
	gcc -c -Wall -Wextra -Werror ft_split.c

ft_strchr.o: ft_strchr.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strchr.c

ft_strdup.o: ft_strdup.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strdup.c

ft_strjoin.o: ft_strjoin.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strjoin.c

ft_strlcat.o: ft_strlcat.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strlcat.c

ft_strlcpy.o: ft_strlcpy.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strlcpy.c

ft_strlen.o: ft_strlen.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strlen.c

ft_strmapi.o: ft_strmapi.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strmapi.c

ft_strncmp.o: ft_strncmp.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strncmp.c

ft_strnstr.o: ft_strnstr.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strnstr.c

ft_strrchr.o: ft_strrchr.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strrchr.c

ft_strtrim.o: ft_strtrim.c libft.h
	gcc -c -Wall -Wextra -Werror ft_strtrim.c

ft_substr.o: ft_substr.c libft.h
	gcc -c -Wall -Wextra -Werror ft_substr.c

ft_tolower.o: ft_tolower.c libft.h
	gcc -c -Wall -Wextra -Werror ft_tolower.c

ft_toupper.o: ft_toupper.c libft.h
	gcc -c -Wall -Wextra -Werror ft_toupper.c

libft.a: $(objects)
	ar -cr libft.a $(objects)

clean:
	rm -rf $(objects) $(bonusobjects)

fclean:
	rm -rf $(objects) $(bonusobjects) libft.a

re: 
	Make fclean
	Make all

bonus: $(objects) $(bonusobjects)
	ar -cr libft.a $(objects) $(bonusobjects)